### ISSUE TITLE
SmartSelfie fails

### ISSUE THREAD

**Issue by D-Ordnance** [smileidentity/flutter#107]
Hi,

I have some issues I don't seem to understand. Before now, I use the `SmartSelfieEnrollment` and it works but now I'm not sure what changes I made `SmartSelfieEnrollment` it always return this error message: **Your selfie failed to process. This could be because of image quality or internet connectivity.**

Please what am I doing wrong?

I would appreciate your swift response.

 Flutter Code
```
Scaffold(
            ...
            ...
            body: SmileIDSmartSelfieEnrollment(
              userId: userId,
              onSuccess: (String? result) {
                ...
                ...
              },
              onError: (String errorMessage) {
                ...
                ...
              },
            ),
 )
```

Android Application Class
```
override fun onCreate() {
        super.onCreate()
        if(BuildConfig.FLAVOR == "dev"){
            SmileID.initialize(this, useSandbox = true)
        }
        else SmileID.initialize(this, useSandbox = false)
    }
```

Flutter smile id version: `smile_id: ^10.0.8`
Android smile Id version: `implementation "com.smileidentity:android-sdk:10.0.4"`

![WhatsApp Image 2024-09-03 at 10 42 09](https://github.com/user-attachments/assets/e227c832-2ee1-4e62-bca5-ac54812bbbec)

**Comment by Xclusivecyborg** [comment]
I am experiencing the same issue too.

**Comment by D-Ordnance** [comment]
Alright @olalekan-agbaje

**Comment by olalekan-agbaje** [comment]
@D-Ordnance 
⚠️ Note: The `smile_config.json` file is unique to the environment (sandbox/production) and api key for which it was created. This means you will need one file for each environment (sandbox/production) of your application.

If you want to work in sandbox, generate a new config for sandbox.

See here: https://docs.usesmileid.com/integration-options/mobile/getting-started#smile-config

**Comment by D-Ordnance** [comment]
Alright, Thanks @olalekan-agbaje

**Comment by D-Ordnance** [comment]
@olalekan-agbaje This has been resolved. Thanks.
