### ISSUE TITLE
iOS Bug White screen in place of camera screen in document capture and selfie

### ISSUE THREAD

**Issue by wcmarieto** [smileidentity/flutter#31]
**Bug Overview:** 

- White screen in place of camera screen in document capture and selfie

**Replication Steps:** 

1. Tapped CTA buttons labeled Take Photo and I'm Ready in SmileIDDocumentVerification widget.

**Flutter SDK Version:** 
>=3.0.3 <4.0.0

**iOS version:** 
14.2

**Comment by vanshg** [comment]
Thanks for the report @wcmarieto. We've identified the cause and have some fixes in the pipeline. We'll update this issue once fully resolved.

**Comment by vanshg** [comment]
Resolved by https://github.com/smileidentity/flutter/releases/tag/v10.0.2
