### ISSUE TITLE
iOS flutter app success Document verification request, but webhook not called

### ISSUE THREAD

**Issue by wcmarieto** [smileidentity/flutter#38]
**Problem:**
   - We have tried approved and rejected scenarios for Document verification w/ webhook integration on iOS. Upon testing, the request to your server is successful, but our webhook is not being called for both approved and rejected scenarios.

**SmileID Environment:** Production

**Job IDs:**
1. JobId: 0000000264, UserId: c71e9512-7a27-47f4-acef-275d812c9116
2. JobId: 0000000266, UserId: 10a6b1e5-9f13-495f-914f-1a776e021e54
3. JobId: 0000000268, UserId: 10a6b1e5-9f13-495f-914f-1a776e021e54
4. JobId: 0000000270, UserId: bbb43f67-68b2-478a-a947-6a3d21ae93f9

![Screenshot 2023-12-21 at 11 49 51 PM](https://github.com/smileidentity/flutter/assets/152957358/03918c3c-c407-4c59-8342-5a517cb18ca2)

**Sample rejected but no webhook call:** https://portal.smileidentity.com/partner/job_results/production/0000000264

Tried in android and everything is fully working including webhooks.
Hope you could assist us.

Thanks!

**Comment by jumaallan** [comment]
Hey @wcmarieto 

Looking into this 

In the meantime, you can set the callback url in the portal and that should work

**Comment by wcmarieto** [comment]
@jumaallan Thanks for that! We were able to verify it and it's now working for iOS using callback URL manually set via portal.  

The only problem we see is that we only have one SmileID account and we have multiple environment stages, each having different callback urls. So it's only a temporary workaround for us but in the long run it would be problematic.

We'll wait for SmileID team's fixes so we can make it work for multiple environments. Thanks!

**Comment by jumaallan** [comment]
@wcmarieto The fix is now ready on iOS

I will do a flutter release tonight and that should fix the issue for you on iOS

**Comment by jumaallan** [comment]
@wcmarieto This release should now fix the bug on iOS - https://github.com/smileidentity/flutter/releases/tag/v10.0.3
