### ISSUE TITLE
SmartSelfie

### ISSUE THREAD

**Issue by D-Ordnance** [smileidentity/flutter#59]
Hi Team,
Please, I need your technical support. I tried integrating your platform using Flutter v10 but I'm facing some bugs on Android.
I keep getting
`[ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.IllegalStateException: ViewTreeLifecycleOwner not found from io.flutter.embedding.android.FlutterView`

I added this to my app's build.gradle
```
dependencies{
....
implementation "com.smileidentity:android-sdk:10.0.4"
...
}
```

Application class
```import android.app.Application
import com.smileidentity.SmileID
class NamedApplication: Application() {
    override fun onCreate() {
        super.onCreate()
        SmileID.initialize(this, useSandbox = true)
    }
}
```
I followed the flutter setup as explained in the documentation

it works fine on iOS
smile_id version: 10.0.8

**Comment by vanshg** [comment]
What is your Activity's parent class? You need to extend from `FlutterFragmentActivity` instead of `FlutterActivity`

**Comment by D-Ordnance** [comment]
I figured out that was the issue, Thank you
