### ISSUE TITLE
Improve JSON response structure

### ISSUE THREAD

**Issue by natintosh** [smileidentity/flutter#70]
### Issue
Improve JSON response structure
Update the `livenessImages` field to use the proper JSON array format instead of a string representation.

Found here
https://github.com/smileidentity/flutter/blob/ea1bc1d44043d9f66df0c03d8a42aac9de97ce6b/ios/Classes/SmileIDSmartSelfieEnrollment.swift#L63

More Details:
The issue seems to be caused by the `livenessImages` field being a string representation of an array instead of a proper JSON array.

Expected Behavior:
The application should be able to parse the JSON response correctly and handle the `livenessImages` field without crashing.

Environment:
- Device: iPhone 11 (iOS 17.X.X)
- Library Version: v10.0.10

Attachments:
[response.json](https://github.com/smileidentity/flutter/files/15300345/response.json)

**Comment by jumaallan** [comment]
We don't get the images from the api/server actually

The array is the file path for the images stored in the device itself, after capture

We can however clean that to represent an actual json array

**Comment by natintosh** [comment]
> The array is the file path for the images stored in the device itself, after capture
> We can however clean that to represent an actual json array

This would be very helpful, it's currently inconsistent with the Android library as that library returns an array of liveness image path
