### ISSUE TITLE
App crashes after document verification

### ISSUE THREAD

**Issue by shettychiragautumn** [smileidentity/flutter#82]
Steps to reproduce:
- Launch App on Flutter
- Click Document Verification button
- Capture front of ID
- Capture back of ID
- Capture Selfie
- Click Proceed button

Expected: Flow proceed as usual
Actual App Crashes

Logs
I/okhttp.OkHttpClient(31048): <-- 400 https://api.smileidentity.com/v1/auth_smile (1021ms, 81-byte body)
E/UtilKt$getExceptionHandler$$inlined$CoroutineExceptionHandler(31048): Error during coroutine execution
E/UtilKt$getExceptionHandler$$inlined$CoroutineExceptionHandler(31048): retrofit2.HttpException: HTTP 400 
E/UtilKt$getExceptionHandler$$inlined$CoroutineExceptionHandler(31048): 	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
E/UtilKt$getExceptionHandler$$inlined$CoroutineExceptionHandler(31048): 	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:164)
E/UtilKt$getExceptionHandler$$inlined$CoroutineExceptionHandler(31048): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
E/UtilKt$getExceptionHandler$$inlined$CoroutineExceptionHandler(31048): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/UtilKt$getExceptionHandler$$inlined$CoroutineExceptionHandler(31048): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/UtilKt$getExceptionHandler$$inlined$CoroutineExceptionHandler(31048): 	at java.lang.Thread.run(Thread.java:920)
E/.flutter.sampl(31048): Invalid ID 0x00000000.
E/AndroidRuntime(31048): FATAL EXCEPTION: main
E/AndroidRuntime(31048): Process: com.smileidentity.flutter.sample, PID: 31048
E/AndroidRuntime(31048): android.content.res.Resources$NotFoundException: String resource ID #0x0
E/AndroidRuntime(31048): 	at android.content.res.Resources.getText(Resources.java:509)
E/AndroidRuntime(31048): 	at android.content.res.Resources.getString(Resources.java:602)
E/AndroidRuntime(31048): 	at androidx.compose.ui.res.StringResources_androidKt.stringResource(StringResources.android.kt:35)
E/AndroidRuntime(31048): 	at com.smileidentity.util.StringResource$DefaultImpls.resolve(Util.kt:315)
E/AndroidRuntime(31048): 	at com.smileidentity.util.StringResource$ResIdFromSmileIDException.resolve(Util.kt:282)
E/AndroidRuntime(31048): 	at com.smileidentity.compose.document.OrchestratedDocumentVerificationScreenKt.OrchestratedDocumentVerificationScreen(OrchestratedDocumentVerificationScreen.kt:114)
E/AndroidRuntime(31048): 	at com.smileidentity.compose.document.OrchestratedDocumentVerificationScreenKt.OrchestratedDocumentVerificationScreen$lambda$19(Unknown Source:35)
E/AndroidRuntime(31048): 	at com.smileidentity.compose.document.OrchestratedDocumentVerificationScreenKt.$r8$lambda$c7rS1cAvhxkYsY3GV_W6YgFrzvU(Unknown Source:0)
E/AndroidRuntime(31048): 	at com.smileidentity.compose.document.OrchestratedDocumentVerificationScreenKt$$ExternalSyntheticLambda6.invoke(Unknown Source:37)
E/AndroidRuntime(31048): 	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
E/AndroidRuntime(31048): 	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2556)
E/AndroidRuntime(31048): 	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2827)
E/AndroidRuntime(31048): 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3314)
E/AndroidRuntime(31048): 	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3265)
E/AndroidRuntime(31048): 	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:940)
E/AndroidRuntime(31048): 	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1155)
E/AndroidRuntime(31048): 	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:127)
E/AndroidRuntime(31048): 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:583)
E/AndroidRuntime(31048): 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:551)
E/AndroidRuntime(31048): 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
E/AndroidRuntime(31048): 	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
E/AndroidRuntime(31048): 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
E/AndroidRuntime(31048): 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
E/AndroidRuntime(31048): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
E/AndroidRuntime(31048): 	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
E/AndroidRuntime(31048): 	at android.view.Choreographer.doFrame(Choreographer.java:792)
E/AndroidRuntime(31048): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
E/AndroidRuntime(31048): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(31048): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31048): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(31048): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(31048): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/AndroidRuntime(31048): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31048): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(31048): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/AndroidRuntime(31048): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@c5a1db3, androidx.compose.ui.platform.MotionDurationScaleImpl@2dd5f70, StandaloneCoroutine{Cancelling}@bf5f2e9, AndroidUiDispatcher@f19b6e]

**Comment by vanshg** [comment]
Thank you for the report. This was fixed in https://github.com/smileidentity/android/pull/392 and we will be releasing an update imminently

**Comment by vanshg** [comment]
Fixed by https://github.com/smileidentity/flutter/pull/83
